<a href="https://colab.research.google.com/github/chengmo03013106/DeepLearning/blob/master/d2l_ch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.1 数据操作: *张量类* : n维数组 (Tensor)

In [ ]:
import torch

In [ ]:
x = torch.arange(12) # arange 创建一个行向量 x
x.shape
x.numel()
X = x.reshape(3,4)
Y = x.reshape(-1,4) # 自动计算

zero = torch.zeros(2,3,4)
one = torch.ones(2,3,4)
ran = torch.randn(3, 4)

print(torch.Tensor([[1,2,3,4],[4,5,6,7]])) # 使用 [[],[],[]] 初始化张量

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.]])


f:R->R 一元标量运算, 函数接收一个输入, 产生一个输出

f:R,R->R 二元标量运算, 函数接收两个输入, 产生一个输出

向量 u, v, 向量c=F(u,v) f 二元运算符


In [ ]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
torch.exp(x) # 求幂
x+y, x-y, x*y, x/y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [ ]:
# 链接两个矩阵
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X,Y), dim=0), torch.cat((X,Y), dim = 1)
# dim = 0, 按轴0, 形状的第一个元素的方向, dim = 1, 按1轴
print(X.shape)
print(Y.shape)

torch.Size([3, 4])
torch.Size([3, 4])


(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [ ]:
X == Y # 逻辑 ==
# torch.tensor([[1,2],[1,2],[1,1],[2,2]]) == torch.tensor([2.0,2.0])
X,Y,X < Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5., 11.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[  2.,  12.,  26.,  36.],
         [ 45.,  57., 124.,  81.],
         [ 92., 102., 112., 122.]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [ ]:
# 求和
torch.tensor([[0.,1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]).sum() # tensor(66.)

tensor(66.)

### 广播机制

In [ ]:
a = torch.arange(8).reshape((4,2))
b = torch.arange(8).reshape((2,4))
#a,b, a+b # ❌️

a = torch.arange(4).reshape((4,1))
b = torch.arange(3).reshape((1,3))
#a,b,a+b # 广播为一个更大的矩阵

In [ ]:
#X[-1],X[1:3] # X.shape(3,4)
X[1,2] = 11
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 11.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
before = id(Y)
Y = Y + X
print(id(Y))
print(before)
Y += X
print(id(Y))

# 数据类型转换  张量 转换其他类型
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

138902122063232
138902122064512
138902122063232


(tensor([3.5000]), 3.5, 3.5, 3)

# 2.2. 数据预处理

In [ ]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')
data_file

'../data/house_tiny.csv'

In [ ]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)
# with open(data_file, 'r') as f:
#   print(f.read())
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
print(inputs.mean(numeric_only=True))
# 必须要有 numeric_only=True, 否则报错,
# 原链接就没有问题吗? https://zh.d2l.ai/chapter_preliminaries/pandas.html
inputs = inputs.fillna(inputs.mean(numeric_only=True))
print("input:",inputs)
inputs = pd.get_dummies(inputs, dummy_na=True)
print("input2:",inputs)
print("out:",outputs)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000
NumRooms    3.0
dtype: float64
input:    NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN
input2:    NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True
out: 0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64


# 2.3. 线性代数
大量文献认为列向量是向量的默认方向，在本书中也是如此

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# 标量
x = torch.tensor(3.0)
y = torch.tensor(2.0)

# 向量

xx = torch.tensor([3.0,2.0])

# 矩阵
YY = torch.tensor([[4.0,5.0],[6.0,7.0]])
ZZ = torch.arange(4).reshape(1,4)
YY[0][1],ZZ[0][2],YY, YY.T # X.T 矩阵转置
# tensor([5])

(tensor(5.),
 tensor(2),
 tensor([[4., 5.],
         [6., 7.]]),
 tensor([[4., 6.],
         [5., 7.]]))

张量（本小节中的“张量”指代数对象）是描述具有任意数量轴的维数组的通用方法
例如 向量是一阶张量，矩阵是二阶张量

 X*Y = [

 a11*b11 a12*b12 ...

 a21*b21 a22*b22 ...

 ...

 ..

 ]

### 通过 sum 进行降维操作

In [ ]:
X = torch.arange(24).reshape(2, 3, 4)
Y = X.clone()
# 将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘。

# 通过 sum 进行降维操作
A_sum_axis0 = X.sum(axis=0) # shape 的 轴0 消失
A_sum_axis1 = X.sum(axis=1)# shape 的 轴1 消失
A_sum_axis2 = X.sum(axis=2)# shape 的 轴2 消失
# X, A_sum_axis0, A_sum_axis0.shape, A_sum_axis1, A_sum_axis1.shape, A_sum_axis2, A_sum_axis2.shape
#X, Y, X*Y, X, X+2, X.sum()-(X+2).sum()
# X, X.sum(axis=[0,1])

# 非降维求和 keepdim=True
A_sum_axis00 = X.sum(axis=0, keepdim=True) # shape 的 轴0 消失
A_sum_axis0.shape, A_sum_axis00.shape


(torch.Size([3, 4]), torch.Size([1, 3, 4]))

In [ ]:
# mean() 也可以指定方向
(X*1.0).mean(axis=0),(X*1.0).mean(axis=1), (X*1.0).mean(axis=2)

(tensor([[ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.],
         [14., 15., 16., 17.]]),
 tensor([[ 4.,  5.,  6.,  7.],
         [16., 17., 18., 19.]]),
 tensor([[ 1.5000,  5.5000,  9.5000],
         [13.5000, 17.5000, 21.5000]]))

In [ ]:
X.numel(), X.sum() / X.numel()

(24, tensor(11.5000))

### 2.3.7 点积 Dot Product

In [ ]:
x = torch.arange(4, dtype=torch.float32)
z = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype = torch.float32)
# 两种写法
x, z, torch.dot(x, z)

(tensor([0., 1., 2., 3.]), tensor([0., 1., 2., 3.]), tensor(14.))

### 2.3.8. 矩阵-向量积

In [ ]:
A = torch.arange(12, dtype=torch.float32).reshape(3,4)
# A, x 执行点积
# 矩阵和向量做点积, 矩阵的每一行和向量依次做点积
# torch.mv = metric * vector
A, x, torch.mv(A,x), # 0*0 + 1*1 + 2*2 + 3*3, 4*0 + 5*1 + 6*2 + 7*3 ...

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([0., 1., 2., 3.]),
 tensor([14., 38., 62.]))

## 2.3.9. 矩阵-矩阵乘法

In [28]:
B=torch.arange(12,dtype=torch.float32).reshape(4,3)
v = torch.tensor([0,1,2,3], dtype=torch.float32)
vv = torch.tensor([0,1,2,3], dtype=torch.float32)+4
vvv = torch.tensor([0,1,2,3], dtype=torch.float32)+4*2
C = torch.mm(A,B)  # mm = metric * metric
# 矩阵乘法 = 后者矩阵退化成向量的向量, 可以看成 矩阵-向量积(向量是后者列轴维度)
A, B, torch.mv(A,v), torch.mv(A,vv), torch.mv(A,vvv), C

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.],
         [ 9., 10., 11.]]),
 tensor([14., 38., 62.]),
 tensor([ 38., 126., 214.]),
 tensor([ 62., 214., 366.]),
 tensor([[ 42.,  48.,  54.],
         [114., 136., 158.],
         [186., 224., 262.]]))

### 2.3.10 范数
* L2 范数 平方根
* L1 范数, L2范数

In [ ]:
# L2 范数 向量元素的平方根
u = torch.tensor([3.0, -4.0])
torch.norm(u)
# L1 范数 向量元素绝对值的和

## 练习
https://zh.d2l.ai/chapter_preliminaries/linear-algebra.html#id17

1. 证明一个矩阵A的转置的转置是(AT)T，即(AT)T== A。

2. 给出两个矩阵A和B，证明“它们转置的和”等于“它们和的转置”，即AT+BT = (A+B)T。

3. 给定任意方阵 ， 总是对称的吗?为什么?

4. 本节中定义了形状(2,3,4)的张量X。len(X)的输出结果是什么？

5. 对于任意形状的张量X,len(X)是否总是对应于X特定轴的长度?这个轴是什么?

6. 运行A/A.sum(axis=1)，看看会发生什么。请分析一下原因？

7. 考虑一个具有形状(2,3,4) 的张量，在轴0、1、2上的求和输出是什么形状?

8. 为linalg.norm函数提供3个或更多轴的张量，并观察其输出。对于任意形状的张量这个函数计算得到什么?


In [52]:
# A, A.T, A.T.T == A
# A,B, A.T+B.T.T == (A+B.T).T
A, A.sum(axis=1), A/A.sum(axis=0)


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 6., 22., 38.]),
 tensor([[0.0000, 0.0667, 0.1111, 0.1429],
         [0.3333, 0.3333, 0.3333, 0.3333],
         [0.6667, 0.6000, 0.5556, 0.5238]]))